name: Lint and Compile

on:
    workflow_dispatch:
    pull_request:
        branches: [main]

jobs:
    Lint-Compile-Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install NPM Packages
              run: npm install

            - name: Run Linter
              run: npm run lint

            - name: Compile TypeScript
              run: npm run compile
